jwt:
  issuer: dontgoback-auth-server
  private-key-path: ./test-keys/private.pem
  public-key-path: ./test-keys/public.pem

auth:
  clients:
    dontgoback-core-server: test-core-secret
    dontgoback-extension-server: test-extension-secret

  #    clientId: clientSecret
